name: Materialize signing key
description: Materializes key to sign assemblies
inputs:
  signing-key-value:
    description: Value of the signing key
    required: true
  signing-key-file-name:
    description: Name of the signing key file
    required: false
    default: key.snk
outputs:
  file-path:
    description: Signing key file path
    value: ${{ steps.signing-key.outputs.PATH }}
runs:
  using: composite
  steps:
    - name: 🖊️ materialize signing key
      id: signing-key
      run: |
        $path = [IO.Path]::Combine("${{ github.workspace }}","src","${{ inputs.signing-key-file-name }}")
        [IO.File]::WriteAllBytes($path, [Convert]::FromBase64String("$env:StrongNameKey"))
        "PATH=$path" >> $env:GITHUB_OUTPUT
      shell: pwsh
      env:
        StrongNameKey: ${{ inputs.signing-key-value }}
