name: Test module & collect code coverage
description: Run tests against specified module collecting code coverage
inputs:
  codecov-token:
    description: Value of Codecov token used to upload code coverage results
    required: true
  coverage-directory:
    description: Path to code coverage directory where results are being stored
    required: false
    default: ${{ github.workspace }}\src\opencover
  module-name:
    description: Name of the module
    required: true
  module-namespace:
    description: Name of the module namespace
    required: true
  target-framework:
    description: Framework version to run tests against
    required: true
runs:
  using: composite
  steps:
    - name: 🧪 test ${{ inputs.module-name }} in ${{ inputs.target-framework }} & collect coverage
      id: test-and-collect-code-coverage
      shell: pwsh
      run: |
        $ErrorActionPreference = 'stop'
        $path = [IO.Path]::Combine("$env:COVERAGE_DIRECTORY", "$env:MODULE_NAMESPACE.$env:MODULE_NAME.xml")
        dotnet test ./src/$env:MODULE_NAMESPACE.$env:MODULE_NAME.Tests/ --no-build -f $env:TARGET_FRAMEWORK -e:CollectCoverage=true -e:CoverletOutputFormat=opencover -e:Exclude="[xunit*]*" -e:CoverletOutput=$path
        "FILE=$env:MODULE_NAMESPACE.$env:MODULE_NAME.$env:TARGET_FRAMEWORK.xml" >> $env:GITHUB_OUTPUT
      env:
        COVERAGE_DIRECTORY: ${{ inputs.coverage-directory }}
        MODULE_NAME: ${{ inputs.module-name }}
        MODULE_NAMESPACE: ${{ inputs.module-namespace }}
        TARGET_FRAMEWORK: ${{ inputs.target-framework }}
    - name: 📤 upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov-token }}
        files: ${{ steps.test-and-collect-code-coverage.outputs.FILE }}
        directory: ${{ inputs.coverage-directory }}
        flags: unittests
