version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "CET"
    groups:
      xUnit:
        patterns:
          - "xunit"
          - "xunit.*"
        exclude-patterns:
          - "xunit.analyzers"
      AutoFixture:
        patterns:
          - "AutoFixture*"
      Analyzers:
        patterns:
          - "*analyzer*"
    ignore:
      - dependency-name: "Moq"
