version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "CET"
    groups:
      xUnit:
        patterns:
          - "xunit"
          - "xunit.*"
          - "xunit.runner.*"
      AutoFixture:
        patterns:
          - "AutoFixture*"
      Analyzers:
        patterns:
          - "*analyzer*"
        exclude-patterns:
          - "xunit.analyzers"
    ignore:
      - dependency-name: "Moq"
    experiments:
      nuget-use-legacy-updater-when-updating-pr: false # Stop using the legacy updater for NuGet packages as it blocks some of the updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
      timezone: "CET"
