version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "CET"
    ignore:
      - dependency-name: "Moq"
