language: "en-US"

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  auto_apply_labels: true
  auto_review:
    enabled: true
    drafts: false
  pre_merge_checks:
    docstrings:
      mode: off
  
chat:
  auto_reply: true
