name: 'Permissions Advisor'

permissions:
  actions: read

on:
  pull_request:
    paths:
    - '.github/workflows/permissions-advisor.yml'
    types: [opened, synchronize, reopened]
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/permissions-advisor.yml'  
  workflow_dispatch:
    inputs:
      name:
        description: 'The name of the workflow file to analyze'
        required: true
        type: string
      count:
        description: 'How many last runs to analyze'
        required: false
        type: number
        default: 10

jobs:
  advisor:
    runs-on: ubuntu-latest
    steps:
    - uses: GitHubSecurityLab/actions-permissions/advisor@v1
      with:
        name: ${{ inputs.name != '' && inputs.name || 'fossa-scan.yml' }}
        count: ${{ inputs.count != '' && inputs.count || 10 }}