name: '🐕‍🦺 Snyk: Vulnerability Analysis'

on:
  pull_request:
    paths:
    - 'src/**'
    - '!src/qodana.yml'
    - '.github/workflows/snyk.yml'
    types: [opened, synchronize, reopened]
  push:
    branches:
    - 'master'
    paths:
    - 'src/**'
    - '!src/qodana.yml'
    - '.github/workflows/snyk.yml'
  schedule:
    - cron: '14 6 * * 0' # Random time
  workflow_dispatch:
  
defaults:
  run:
    shell: pwsh

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: 📥 checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 
      - name: 🏗️ restore dependencies
        run: |
          $ErrorActionPreference = 'stop'
          dotnet restore ./src/Objectivity.AutoFixture.XUnit2.AutoMock.sln
          if ($LastExitCode -ne 0) {
            throw "dotnet restore failed with exit code $LastExitCode"
          }
      - name: 🏗️ setup snyk
        uses: snyk/actions/setup@master
      - name: 🔬 snyk opensource scan
        run: snyk test --sarif-file-output=snyk/opensource.sarif --all-projects --exclude=Objectivity.AutoFixture.XUnit2.AutoFakeItEasy.Tests,Objectivity.AutoFixture.XUnit2.AutoMoq.Tests,Objectivity.AutoFixture.XUnit2.AutoNSubstitute.Tests,Objectivity.AutoFixture.XUnit2.Core.Tests
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: 🔬 snyk code scan
        run: snyk code test --sarif-file-output=snyk/code.sarif
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: 📈 snyk monitor
        run: snyk monitor --all-projects --exclude=Objectivity.AutoFixture.XUnit2.AutoFakeItEasy.Tests,Objectivity.AutoFixture.XUnit2.AutoMoq.Tests,Objectivity.AutoFixture.XUnit2.AutoNSubstitute.Tests,Objectivity.AutoFixture.XUnit2.Core.Tests
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: 📊 upload opensource sarif for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk/opensource.sarif
          category: snyk-opensource
        if: ${{ always() }}
      - name: 📊 upload code sarif for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk/code.sarif
          category: snyk-code
        if: ${{ always() }}
